### ISSUE TITLE
The method 'pop' was called on null

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#230]
![Screenshot_20190502_191650_xyz apollotv kamino](https://user-images.githubusercontent.com/30179692/57073625-85ccb800-6cd9-11e9-9b46-c28d1d657878.jpg)

**Comment by SpajicM** [comment]
Should be fixed by https://github.com/ApolloTVofficial/kamino/commit/05d71cb75307e01c8404731e90e51b5660f5cade#diff-ef350a883be1b6f36c84a7940b65158bR255

I'm not sure at which exact commit the release version stands?

**Comment by kevincosmos** [comment]
Closing as this should be resolved

**Comment by NBTX** [comment]
The commit was before the release so the bug is likely still present

**Comment by NBTX** [comment]
From Facebook: "Minor one, go to connect RD and then close the page before logging in, app crashes."

**Comment by NBTX** [comment]
Assuming fixed in v1.4.5
